### ISSUE TITLE
Починить новую сборку: time.split и duration

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast#20]
Заметил, что после [добавления данных об MP3-файлах](https://github.com/web-standards-ru/podcast/commit/1eaae2a1a293569bf268f3b11da6217ffc981a78) сборка начала падать с ошибкой про `time.split`. Возможно дело в ключе duration — такое же имя используется при сборке фида и вызывает фильтр, который форматирует время. Но не уверен сходу.

```
npm run build

> build
> eleventy

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering 11ty.js template ./src/feed.11ty.js (via TemplateContentRenderError)
[11ty] 2. time.split is not a function (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: time.split is not a function
[11ty]     at Object.<anonymous> (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/eleventy.config.js:21:15)
[11ty]     at Object.<anonymous> (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:35:23)
[11ty]     at Object.duration (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:126:14)
[11ty]     at file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/src/feed.11ty.js:37:31
[11ty]     at async Promise.all (index 61)
[11ty]     at async Object.getEpisodes (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/src/feed.11ty.js:9:18)
[11ty]     at async Object.render (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/src/feed.11ty.js:100:8)
[11ty]     at async Template._render (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/node_modules/@11ty/eleventy/src/TemplateContent.js:569:19)
[11ty]     at async Template.renderPageEntryWithoutLayout (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/node_modules/@11ty/eleventy/src/Template.js:417:25)
[11ty]     at async TemplateMap.populateContentDataInMap (file:///Users/pepelsbey/Documents/Web%20Standards/%D0%9A%D0%BE%D0%B4/podcast/node_modules/@11ty/eleventy/src/TemplateMap.js:540:7)
[11ty] Wrote 0 files in 0.47 seconds (v3.0.0-alpha.6)
```

@monochromer можешь глянуть, плиз? Не горит, я пока на предыдущей версии соберу свежий выпуск)

**Comment by monochromer** [comment]
@pepelsbey, должно пофиксить - https://github.com/web-standards-ru/podcast/pull/21
